name = "backstage-cron"
main = "worker/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "3ed9d60408c24ed6b557ff4123a32978"

[triggers]
crons = ["0 8 * * *"]
